name: .NET

env:
  TEST_FILES_PATH: /home/runner/work/AlgorithmDLX/AlgorithmDLX/AlgorithmDLX.UnitTest/TestFiles/

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -f net8.0-windows
    - name: Test
      run: dotnet test --no-build --verbosity normal